// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/autotune/gen_harness.py from ops/gemm_square.toml -- do not edit.
//
// Standalone autotuner harness: drives the Quidditch dispatch (compute + DMA
// fan-out across the 8 compute cores) for the IREE-generated gemm64 kernel
// DIRECTLY, without the IREE VM/HAL/loader/context, and prints the dispatch
// cycle count (the autotuner's metric). Mirrors the Snitch branch of
// quidditch_executable_issue_dispatch_inline (executable.c).
//
// Correctness is a Tier-1 gate: structured-integer inputs (distinct, asymmetric
// in every index) keep the exact result representable in f64, and the output is
// compared PER ELEMENT against a host reference -- so transpose / index-swap /
// operand-swap miscompiles a symmetric all-ones input would hide are caught.

#include <Quidditch/dispatch/dispatch.h>
#include <Quidditch/executable/executable_library.h>
#include <iree/base/api.h>
#include <iree/hal/local/executable_library.h>

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <encoding.h>    // read_csr(mcycle)
#include <team_decls.h>  // snrt_is_dm_core, snrt_cluster_compute_core_num

#include <gemm_mod.h>  // quidditch_gemm64_dispatch_0_library_query

#define MM 16
#define NN 16
#define KK 16
typedef double elem_t;

// Workgroup-local scratch. Kept small: static bss is zeroed at boot and a large
// buffer alone adds tens of thousands of boot cycles to the sim.
#define LOCAL_MEMORY_BYTES (16 * 1024)
static iree_alignas(64) uint8_t g_local_memory[LOCAL_MEMORY_BYTES];

int main(void) {
  static iree_alignas(64) elem_t A[MM * KK];
  static iree_alignas(64) elem_t B[NN * KK];
  static iree_alignas(64) elem_t C[MM * NN];

  // The 8 compute cores park in the worker loop; the DM core drives below.
  if (!snrt_is_dm_core()) return quidditch_dispatch_enter_worker_loop();

  // ---- DM core only ----
  for (int i = 0; i < MM; i++)
    for (int k = 0; k < KK; k++)
      A[i * KK + k] = (elem_t)(i * KK + k + 1);
  for (int j = 0; j < NN; j++)
    for (int k = 0; k < KK; k++)
      B[j * KK + k] = (elem_t)(k * NN + j + 1);
  for (int idx = 0; idx < MM * NN; idx++) C[idx] = (elem_t)0;

  // Query the generated library directly (no VM/HAL/loader).
  iree_hal_executable_environment_v0_t environment;
  memset(&environment, 0, sizeof(environment));
  const iree_hal_executable_library_header_t** header =
      quidditch_gemm64_dispatch_0_library_query(
          IREE_HAL_EXECUTABLE_LIBRARY_VERSION_LATEST, &environment);
  const quidditch_executable_library_v0_t* lib =
      (const quidditch_executable_library_v0_t*)header;

  const iree_host_size_t ordinal = 0;
  iree_hal_executable_dispatch_attrs_v0_t attrs = lib->exports.attrs[ordinal];
  size_t local_memory_size = (size_t)attrs.local_memory_pages * 4096;
  if (local_memory_size > sizeof(g_local_memory)) {
    printf("HARNESS ERROR: local_memory_pages=%u exceeds scratch\n",
           (unsigned)attrs.local_memory_pages);
    return 2;
  }
  if (attrs.binding_count != 3) {
    printf("HARNESS ERROR: binding_count=%u expected 3\n",
           (unsigned)attrs.binding_count);
    return 2;
  }

  // Build the dispatch state by hand (what command_buffer.c does).
  void* binding_ptrs[3] = {A, B, C};
  size_t binding_lengths[3] = {sizeof(A), sizeof(B), sizeof(C)};
  iree_alignas(64) iree_hal_executable_dispatch_state_v0_t dispatch_state;
  memset(&dispatch_state, 0, sizeof(dispatch_state));
  dispatch_state.workgroup_size_x = attrs.workgroup_size_x ? attrs.workgroup_size_x : 1;
  dispatch_state.workgroup_size_y = attrs.workgroup_size_y ? attrs.workgroup_size_y : 1;
  dispatch_state.workgroup_size_z = attrs.workgroup_size_z ? attrs.workgroup_size_z : 1;
  dispatch_state.workgroup_count_x = 1;
  dispatch_state.workgroup_count_y = 1;
  dispatch_state.workgroup_count_z = 1;
  dispatch_state.max_concurrency = snrt_cluster_compute_core_num();
  dispatch_state.constant_count = attrs.constant_count;
  dispatch_state.constants = NULL;
  dispatch_state.binding_count = attrs.binding_count;
  dispatch_state.binding_ptrs = binding_ptrs;
  dispatch_state.binding_lengths = binding_lengths;

  iree_hal_executable_dispatch_v0_t compute_fn = lib->exports.compute_core_ptrs[ordinal];
  iree_hal_executable_dispatch_v0_t dma_fn = lib->exports.dma_core_ptrs[ordinal];
  quidditch_dispatch_set_kernel(compute_fn, &environment, &dispatch_state);

  iree_hal_executable_workgroup_state_v0_t workgroup_state;
  memset(&workgroup_state, 0, sizeof(workgroup_state));
  workgroup_state.local_memory = g_local_memory;
  workgroup_state.local_memory_size = (uint32_t)local_memory_size;

  // ---- ROI: one workgroup (1,1,1), Snitch fan-out (mirrors executable.c) ----
  uint32_t t0 = read_csr(mcycle);
  if (dma_fn) {
    quidditch_dispatch_queue_subgroups(&workgroup_state);  // releases compute cores
    dma_fn(&environment, &dispatch_state, &workgroup_state);  // DM core's DMA half
    quidditch_dispatch_wait_for_workgroup();                  // rejoin
  } else {
    quidditch_dispatch_queue_workgroup(&workgroup_state);
    quidditch_dispatch_execute_workgroups();
  }
  uint32_t t1 = read_csr(mcycle);

  quidditch_dispatch_quit();  // release the parked compute cores at shutdown

  // ---- Tier-1 correctness: per-element exact INTEGER compare vs host reference.
  // Reference and compare use integer mul/add + fcvt.w.d only: the structured
  // inputs are exact integers, the Snitch FPU has no fdiv, and FP arithmetic on
  // the DM core is avoided. Relative-tolerance fp checks are host-side (Tier-2).
  int errors = 0;
  int first_i = -1, first_j = -1, first_got = 0, first_want = 0;
  for (int i = 0; i < MM; i++)
    for (int j = 0; j < NN; j++) {
      int want = 0;
      for (int k = 0; k < KK; k++)
        want += (int)A[i * KK + k] * (int)B[j * KK + k];
      int got = (int)C[i * NN + j];
      if (got != want) {
        if (first_i < 0) { first_i = i; first_j = j; first_got = got; first_want = want; }
        errors++;
      }
    }

  printf("[HARNESS] dispatch_cycles=%u local_pages=%u errors=%d/%d -> %s\n",
         t1 - t0, (unsigned)attrs.local_memory_pages, errors, MM * NN,
         errors ? "FAIL" : "SUCCESS");
  if (errors)
    printf("[HARNESS] first mismatch (%d,%d) got=%d want=%d\n",
           first_i, first_j, first_got, first_want);
  return errors ? 1 : 0;
}
